'use strict';
const $=id=>document.getElementById(id);
const events=[
 {sol:1,type:'MISSION PRELUDE',place:'ARES III',status:'CREWED SURFACE OPS',title:'Six people. One working outpost.',copy:'The Ares III crew begins routine surface work in Acidalia Planitia. These opening sols are a calm editorial prelude; the film first labels the mission at Sol 18.',note:'Every survival story starts before anyone knows survival will be required.',hab:'NOMINAL',food:'MISSION STOCK',comms:'HERMES LINK',dist:0,stop:0},
 {sol:18,type:'INCIDENT LOG',place:'ARES III',status:'MISSION ABORT',title:'The storm changes everything.',copy:'A violent storm forces the crew to abort. Watney is struck, presumed dead and left behind when the ascent vehicle departs.',note:'The mission ends. The survival mission begins.',hab:'OFFLINE CHECK',food:'UNKNOWN',comms:'NO LINK',dist:1,stop:0},
 {sol:21,type:'SURVIVAL LOG',place:'THE HAB',status:'ALONE',title:'Take inventory. Make a plan.',copy:'Alive and alone, he counts food, checks the Hab and confronts the calendar. The next mission is years away; the existing supplies are not.',note:'Solve the first problem, then the next one.',hab:'SEALED',food:'~400 SOLS',comms:'NONE',dist:2,stop:0},
 {sol:31,type:'BOTANY LOG',place:'THE HAB',status:'CROP PLANTED',title:'Bring life to dead soil.',copy:'Martian soil, Earth compost and saved potatoes turn the Hab into an improvised farm. The crop is a bridge between the food he has and the food he needs.',note:'On a world where nothing grows, the botanist plants anyway.',hab:'GREENHOUSE',food:'CROP STARTED',comms:'NONE',dist:3,stop:0},
 {sol:36,type:'ENGINEERING LOG',place:'THE HAB',status:'WATER PRODUCTION',title:'Make the missing ingredient.',copy:'The new field needs water. Hydrazine, chemistry and careful improvisation create it—after a close lesson in how quickly a calculation can become a fire.',note:'Every resource on Mars has to be found, made or saved.',hab:'HUMID',food:'CROP GROWING',comms:'NONE',dist:3,stop:0},
 {sol:54,type:'BOTANY LOG',place:'THE HAB',status:'FIRST SPROUT',title:'Green appears on Mars.',copy:'A first shoot breaks through the soil. Orbiting observers also recognize that the supposedly abandoned Hab is active.',note:'One green leaf is both food and a signal.',hab:'GREENHOUSE',food:'IMPROVING',comms:'OBSERVED',dist:4,stop:0},
 {sol:79,type:'EXPEDITION LOG',place:'CHRYSE PLANITIA',status:'PATHFINDER PLAN',title:'A dead spacecraft can still speak.',copy:'With a healthy crop but no way to call home, he studies old mission maps and sets out for the long-silent Mars Pathfinder lander.',note:'The solution has been waiting in the dust since 1997.',hab:'STABLE',food:'400 PLANTS',comms:'SEARCHING',dist:120,stop:1},
 {sol:109,type:'COMMS LOG',place:'PATHFINDER',status:'SIGNAL ACQUIRED',title:'Earth answers.',copy:'Pathfinder wakes. Its high-gain antenna turns toward Earth, and an old machine becomes a new communications bridge.',note:'For the first time since the storm, alone no longer means unheard.',hab:'STABLE',food:'CROP ACTIVE',comms:'PATHFINDER',dist:800,stop:1},
 {sol:128,type:'OPERATIONS LOG',place:'THE HAB',status:'EARTH SUPPORT',title:'The whole planet joins the problem.',copy:'NASA can now send instructions and help manage the crop. The Hab is lush, green and connected—a fragile island of life.',note:'One survivor now has a room full of minds on Earth.',hab:'GREENHOUSE',food:'MANAGED',comms:'TEXT LINK',dist:1600,stop:0},
 {sol:154,type:'RATION LOG',place:'THE HAB',status:'MINIMUM CALORIES',title:'Turn days into portions.',copy:'Food becomes arithmetic. Rations are divided and stretched while Earth races to send supplies.',note:'Survival can look like one meal split into three.',hab:'DAMAGED',food:'CRITICAL',comms:'TEXT LINK',dist:1600,stop:0},
 {sol:186,type:'DECISION LOG',place:'THE HAB',status:'RESCUE UNCERTAIN',title:'Prepare for every outcome.',copy:'With rescue still uncertain, private messages carry the weight of distance. The work continues because stopping cannot improve the odds.',note:'Hope is useful when it becomes another task.',hab:'REPAIRED',food:'CRITICAL',comms:'TEXT LINK',dist:1600,stop:0},
 {sol:219,type:'RESCUE PLAN',place:'THE HAB',status:'ARES IV TARGET',title:'The way home is 3,200 kilometres away.',copy:'The Ares IV ascent vehicle is waiting at Schiaparelli. The new problem is a continental drive with every life-support system packed into the rover.',note:'The Hab kept him alive. Now he has to take it apart.',hab:'BEING STRIPPED',food:'RATIONED',comms:'EARTH LINK',dist:1600,stop:0},
 {sol:461,type:'DEPARTURE LOG',place:'ACIDALIA PLANITIA',status:'LONG-RANGE CROSSING',title:'Leave the only home on Mars.',copy:'Two rovers become a caravan. The Hab gives up equipment and canvas. The journey to Schiaparelli begins.',note:'Home is no longer a place. It is whatever keeps moving.',hab:'ABANDONED',food:'FINAL STORES',comms:'MOBILE LINK',dist:1620,stop:2},
 {sol:494,type:'ROVER LOG',place:'MARS CROSSING',status:'IN TRANSIT',title:'Drive. Charge. Sleep. Repeat.',copy:'Four hours of driving before noon, then thirteen hours of solar charging. The rover crosses an empty world at no more than 25 kilometres per hour.',note:'For a while, it is the only moving thing on the planet.',hab:'3200 KM BEHIND',food:'FINAL STORES',comms:'MOBILE LINK',dist:2450,stop:3},
 {sol:538,type:'ASCENT LOG',place:'SCHIAPARELLI',status:'MAV MODIFICATION',title:'Remove everything that is not escape.',copy:'At the Ares IV site, the ascent vehicle is stripped to reach the speed required for the Hermes intercept.',note:'The last machine on Mars only has to work once.',hab:'—',food:'LAST RATIONS',comms:'ARES IV LINK',dist:4800,stop:4},
 {sol:560,type:'INTERCEPT LOG',place:'SCHIAPARELLI',status:'HERMES INBOUND',title:'The crew comes back.',copy:'Hermes reaches Mars. The ascent and intercept plan leaves almost no margin, but every team member now has one role: bring him home.',note:'After 542 sols alone, the sky contains familiar voices.',hab:'—',food:'1 RATION',comms:'HERMES LINK',dist:4800,stop:4},
 {sol:561,type:'FINAL SURFACE LOG',place:'SCHIAPARELLI',status:'LAUNCH DAY',title:'Goodbye, Mars.',copy:'The last ration is opened. The improvised ascent vehicle launches toward Hermes and the long surface chronicle ends above the planet.',note:'A planet of problems, solved one at a time.',hab:'—',food:'DEPLETED',comms:'HERMES LINK',dist:4800,stop:4}
];
const stops=[
 {name:'Ares III Hab',tag:'WAYPOINT 01 / ACIDALIA',coord:'31.2°N · 28.5°W / FICTIONAL',x:185,y:180,sol:18,copy:'The expedition begins and the survival problem takes shape here. The site becomes shelter, workshop, farm and eventually a source of parts for the escape.',facts:[['ROLE','SURFACE HOME'],['DURATION','443+ SOLS'],['STATUS','ABANDONED']]},
 {name:'Pathfinder',tag:'WAYPOINT 02 / CHRYSE',coord:'REAL 1997 LANDING REGION',x:420,y:338,sol:109,copy:'The 1997 lander becomes a bridge between a stranded astronaut and Earth. NASA notes that the fictional Ares III site lies roughly 800 kilometres from Pathfinder.',facts:[['ROLE','COMMS BRIDGE'],['LEGACY','1997 MISSION'],['SIGNAL','REACQUIRED']]},
 {name:'Marth Crater',tag:'WAYPOINT 03 / CROSSING',coord:'ROUTE LANDMARK / SCHEMATIC',x:565,y:419,sol:494,copy:'A dramatic landmark along the long rover crossing. The map compresses the route into an editorial path; its terrain and stop positions are illustrative.',facts:[['ROLE','ROUTE MARKER'],['POWER','SOLAR'],['PACE','25 KM/H MAX']]},
 {name:'Rover Camp',tag:'WAYPOINT 04 / TRANSIT',coord:'MOBILE CAMP / SCHEMATIC',x:675,y:350,sol:494,copy:'Each driving day becomes a loop: move before noon, deploy panels, wait through the charge, sleep, and begin again.',facts:[['DRIVE','4 HOURS'],['CHARGE','13 HOURS'],['HOME','PRESSURISED ROVER']]},
 {name:'Schiaparelli',tag:'WAYPOINT 05 / ARES IV',coord:'ARES IV MAV SITE / FICTIONAL',x:775,y:170,sol:561,copy:'The Ares IV ascent vehicle waits here. Reaching it completes the 3,200-kilometre escape route; launching from it begins the final intercept.',facts:[['ROLE','ASCENT SITE'],['ARRIVAL','SOL 538'],['LAUNCH','SOL 561']]}
];
const systems=[
 {title:'Life support',copy:'The oxygenator, atmospheric regulator and water reclaimer turn a sealed volume into a place a human can occupy. Losing any one changes the survival clock immediately.',x:198,y:164,gauge:100},
 {title:'The farm',copy:'Shelves, bunks and floor become growing area. The crop converts stored potatoes, treated soil, water and time into additional food.',x:322,y:245,gauge:82},
 {title:'Power grid',copy:'External solar arrays charge batteries for the Hab and rover. Dust, distance and charging time shape what can happen each sol.',x:92,y:245,gauge:74},
 {title:'Communications',copy:'The original link is gone after the abort. Pathfinder restores a narrow connection, and later the rover carries that lifeline across the planet.',x:545,y:135,gauge:68},
 {title:'Airlocks',copy:'Every crossing between shelter and Mars passes through a pressure boundary. A seal is a door only while every component holds.',x:675,y:222,gauge:94}
];
let selectedSol=1,currentEvent=0,currentStop=0,currentSystem=0,followTimer=null;
function nearestIndex(sol){let best=0;events.forEach((e,i)=>{if(Math.abs(e.sol-sol)<Math.abs(events[best].sol-sol))best=i});return best}
function formatDuration(sol){const days=Math.round(sol*1.02749),years=Math.floor(days/365),months=Math.floor((days%365)/30),d=(days%365)%30;return String(years).padStart(2,'0')+' YEARS · '+String(months).padStart(2,'0')+' MONTHS · '+String(d).padStart(2,'0')+' DAYS'}
function renderEvent(sol,scroll=false){selectedSol=Math.max(1,Math.min(561,sol));currentEvent=nearestIndex(selectedSol);const e=events[currentEvent];$('sol-slider').value=selectedSol;$('sol-number').textContent=selectedSol;$('earth-day').textContent=formatDuration(selectedSol);$('log-type').textContent=e.type;$('log-coord').textContent=e.place;$('event-sol').textContent='SOL '+e.sol;$('event-status').textContent=e.status;$('event-title').textContent=e.title;$('event-copy').textContent=e.copy;$('event-note').textContent=e.note;$('hab-status').textContent=e.hab;$('food-status').textContent=e.food;$('comms-status').textContent=e.comms;$('distance').textContent=e.dist.toLocaleString()+' KM';document.querySelectorAll('#jump-row button').forEach(b=>b.classList.toggle('active',Number(b.dataset.sol)===e.sol));updateRoute(selectedSol);if(scroll)$('chronicle').scrollIntoView({behavior:'smooth',block:'start'})}
function buildJumps(){[1,18,54,109,219,461,538,561].forEach(sol=>{const b=document.createElement('button');b.textContent='S'+sol;b.dataset.sol=sol;b.onclick=()=>renderEvent(sol);$('jump-row').append(b)})}
function renderStops(){const g=$('map-stops');g.innerHTML='';stops.forEach((s,i)=>{const n=document.createElementNS('http://www.w3.org/2000/svg','g');n.setAttribute('class','map-stop '+(i===currentStop?'active':''));n.setAttribute('transform',`translate(${s.x} ${s.y})`);n.setAttribute('tabindex','0');n.setAttribute('role','button');n.setAttribute('aria-label','Open '+s.name);n.innerHTML=`<circle r="7"/><text x="13" y="-5">${s.name.toUpperCase()}</text><text class="sub" x="13" y="8">SOL ${s.sol}</text>`;n.onclick=()=>selectStop(i);n.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectStop(i)}};g.append(n)});const s=stops[currentStop];$('waypoint-tag').textContent=s.tag;$('waypoint-coord').textContent=s.coord;$('waypoint-title').textContent=s.name;$('waypoint-copy').textContent=s.copy;$('waypoint-facts').innerHTML=s.facts.map(([a,b])=>`<div><span>${a}</span><b>${b}</b></div>`).join('');$('open-log').onclick=()=>renderEvent(s.sol,true)}
function selectStop(i){currentStop=i;renderStops();positionRover(i/(stops.length-1))}
function positionRover(t){const path=$('route'),len=path.getTotalLength?path.getTotalLength():750,p=path.getPointAtLength?path.getPointAtLength(len*t):{x:185+(775-185)*t,y:180};$('rover-marker').style.transform=`translate(${p.x}px,${p.y}px)`}
function updateRoute(sol){const path=$('route-progress'),len=path.getTotalLength?path.getTotalLength():750;let t=0;if(sol>=461)t=Math.min(1,(sol-461)/77);else if(sol>=79&&sol<=109)t=.4*(sol-79)/30;else if(sol>109&&sol<461)t=.4;path.style.strokeDasharray=len;path.style.strokeDashoffset=len*(1-t);positionRover(t)}
function renderSystems(){const g=$('hab-hotspots');g.innerHTML='';systems.forEach((s,i)=>{const n=document.createElementNS('http://www.w3.org/2000/svg','g');n.setAttribute('class','hab-hotspot '+(i===currentSystem?'active':''));n.setAttribute('transform',`translate(${s.x} ${s.y})`);n.setAttribute('tabindex','0');n.setAttribute('role','button');n.setAttribute('aria-label','Inspect '+s.title);n.innerHTML=`<circle r="12"/><text x="18" y="3">0${i+1}</text>`;n.onclick=()=>{currentSystem=i;renderSystems()};n.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();n.onclick()}};g.append(n)});const s=systems[currentSystem];$('system-number').textContent='SYSTEM 0'+(currentSystem+1);$('system-title').textContent=s.title;$('system-copy').textContent=s.copy;$('system-gauge').style.width=s.gauge+'%'}
function show(html){$('modal-content').innerHTML=html;if(!$('modal').open)$('modal').showModal()}
$('sol-slider').oninput=e=>renderEvent(Number(e.target.value));$('next-event').onclick=()=>renderEvent(events[(currentEvent+1)%events.length].sol);$('cycle-system').onclick=()=>{currentSystem=(currentSystem+1)%systems.length;renderSystems()};$('follow').onclick=()=>{clearInterval(followTimer);let i=0;selectStop(0);$('follow').innerHTML='Following route <span>●</span>';followTimer=setInterval(()=>{i++;if(i>=stops.length){clearInterval(followTimer);$('follow').innerHTML='Follow route <span>▶</span>';return}selectStop(i)},1400)};
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>$(b.dataset.go).scrollIntoView({behavior:'smooth'}));
const lightboxes={landscape:['assets/mars-landscape.webp','The landscape','A cinematic, original study of Mars as an immense and indifferent environment. The lone astronaut is deliberately anonymous.'],rover:['assets/long-range-rover.webp','The long-range rover','An original vehicle concept built around the needs of a sustained crossing: pressure, power, storage, traction and repair access.'],habitat:['assets/mars-habitat.webp','The surface habitat','An original near-future habitat study with a pressurised living volume, power array, communications mast and external stores.']};document.querySelectorAll('[data-lightbox]').forEach(b=>b.onclick=()=>{const x=lightboxes[b.dataset.lightbox];show(`<img class="modal-img" src="${x[0]}" alt="${x[1]}"><div class="modal-copy"><div class="eyebrow">ORIGINAL VISUAL STUDY</div><h2>${x[1]}</h2><p>${x[2]}</p></div>`)});
$('about').onclick=()=>show(`<div class="modal-copy"><div class="eyebrow">MISSION NOTES</div><h2>Where story meets Mars science.</h2><p>This independent interactive chronicle is inspired by the 2015 film <i>The Martian</i>, starring Matt Damon as Mark Watney. It summarises plot milestones and contains spoilers.</p><p>The displayed event sols follow the film’s shooting script: the storm on Sol 18, crops and Pathfinder, the long rover crossing, and the Sol 561 launch. Sols between recorded milestones are a browsable mission clock rather than separate invented plot events.</p><p>The map is deliberately schematic. A NASA article places the fictional Ares III site about 800 kilometres from the real Pathfinder landing site; the screenplay describes the Ares IV ascent vehicle as 3,200 kilometres from the Hab. The cumulative distance readout is an editorial estimate that includes the Pathfinder round trip.</p><p>The one-way Earth delay is presented as 12 minutes at the rescue, matching the screenplay scene. Real Mars communications delay varies with the planets’ positions.</p><p>All three landscape images are newly generated for this experience. They are original exploration concepts and do not reproduce actors, film stills or production designs.</p><div class="mission-list"><div><b>NASA</b><span>REAL TECHNOLOGIES IN THE MARTIAN</span></div><div><b>NASA APOD</b><span>FICTIONAL ARES III SITE</span></div><div><b>2015 SCRIPT</b><span>DISPLAYED SOL MILESTONES</span></div><div><b>EDITORIAL</b><span>ROUTE + SYSTEM DIAGRAMS</span></div></div><p><a href="https://www.nasa.gov/stem-content/nine-real-nasa-technologies-in-the-martian/" target="_blank" rel="noopener">Read NASA’s technology notes ↗</a></p></div>`);
$('close-modal').onclick=()=>$('modal').close();$('modal').addEventListener('click',e=>{if(e.target===$('modal'))$('modal').close()});buildJumps();renderEvent(1);renderStops();renderSystems();
